name = "arb-stats"
main = "src/index.ts"
workers_dev = true
compatibility_date = "2024-01-29"

routes = [
	{ pattern = "arb-stats.shitzuapes.xyz", custom_domain = true }
]

[vars]
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these

[durable_objects]
bindings = [
  { name = "INFO", class_name = "Info" },
  { name = "BOTS", class_name = "Bots" },
]

[[migrations]]
tag = "v1"
new_classes = ["Info", "Bots"]
